<?php

namespace Omnipay\Payture\Exception\en;

use Omnipay\Payture\Exception\LocalizedError;
use Omnipay\Payture\Exception\SystemError;

/**
 * Payture protocol errors english localization.
 */
class HumanError extends LocalizedError
{
    protected static $_errors = [
        SystemError::SUCCESS => null,
        SystemError::UNKNOWN => 'Sorry, currently the payment with the card is impossible. Try another card',
        SystemError::ACCESS_DENIED => 'Operations with selected parameters are forbidden via terminal',
        SystemError::AMOUNT_ERROR => 'Transaction amount error. Amount exceeded or transaction amount not verified',
        SystemError::AMOUNT_EXCEED => 'Transaction amount exceeds available balance on selected account',
        SystemError::API_NOT_ALLOWED => 'Use of payment API forbidden from this IP. Please check access details',
        SystemError::CARD_EXPIRED => 'Card expired',
        SystemError::CARD_NOT_FOUND => 'Card with given ID not found',
        SystemError::COMMUNICATE_ERROR => 'Communication error in physical channels',
        SystemError::CURRENCY_NOT_ALLOWED => 'Currency forbidden for enterprise',
        SystemError::CUSTOMER_NOT_FOUND => 'User not found',
        SystemError::DUPLICATE_CARD => 'Card already exists',
        SystemError::DUPLICATE_ORDER_ID => 'Order exists in Payture with the following ID',
        SystemError::DUPLICATE_PROCESSING_ORDER_ID => 'Order exists in processing with the following ID',
        SystemError::DUPLICATE_USER => 'User already exists',
        SystemError::EMAIL_ERROR => 'Error processing email. Error sendind message',
        SystemError::EMPTY_RESPONSE => 'Empty processing response',
        SystemError::FRAUD_ERROR => 'Anti-fraud error',
        SystemError::FRAUD_ERROR_BIN_LIMIT => 'Limit of payments via 1 bank exceeded',
        SystemError::FRAUD_ERROR_BLACKLIST_AEROPORT => 'Airport blacklisted for fraud',
        SystemError::FRAUD_ERROR_BLACKLIST_BANKCOUNTRY => 'Bank’s country blacklisted for fraud',
        SystemError::FRAUD_ERROR_BLACKLIST_USERCOUNTRY => 'User’s country blacklisted for fraud',
        SystemError::FRAUD_ERROR_CRITICAL_CARD => 'Card flagged for fraud',
        SystemError::FRAUD_ERROR_CRITICAL_CUSTOMER => 'User flagged for fraud',
        SystemError::FRAUD_ERROR_IP => 'IP flagged for fraud',
        SystemError::FRAUD_INTERNAL_ERROR => 'Anti-fraud filter error during payment processing',
        SystemError::ILLEGAL_ORDER_STATE => 'Invalid order status',
        SystemError::INTERNAL_ERROR => 'Internal gateway error',
        SystemError::INVALID_PAYTUREID => 'Invalid device fingerprint',
        SystemError::INVALID_SIGNATURE => 'Invalid request signature',
        SystemError::ISSUER_BLOCKED_CARD => 'Card blocked by issuing bank',
        SystemError::ISSUER_CARD_FAIL => 'Issuing bank could not allow debiting of card',
        SystemError::ISSUER_FAIL => 'No response from issuing bank',
        SystemError::ISSUER_LIMIT_AMOUNT_FAIL => 'Exceeded transaction limits with issuing bank',
        SystemError::ISSUER_LIMIT_COUNT_FAIL => 'Exceeded limits on number of transactions with issuing bank',
        SystemError::ISSUER_LIMIT_FAIL => 'Exceeded limits with issuing bank',
        SystemError::ISSUER_TIMEOUT => 'Issuing bank response timeout',
        SystemError::MERCHANT_FORWARD => 'Redirecting to another terminal',
        SystemError::MERCHANT_RESTRICTION => 'Merchant banned by acquiring bank or MPS',
        SystemError::MPI_CERTIFICATE_ERROR => 'MPI (gateway) service error',
        SystemError::MPI_RESPONSE_ERROR => 'MPI (MPS) service error',
        SystemError::ORDER_NOT_FOUND => 'Order not found',
        SystemError::ORDER_TIME_OUT => 'Order expired',
        SystemError::PAYMENT_ENGINE_ERROR => 'Interoperability error in processing core',
        SystemError::PROCESSING_ACCESS_DENIED => 'Processing access denied',
        SystemError::PROCESSING_ERROR => 'Error during transaction processing',
        SystemError::PROCESSING_FRAUD_ERROR => 'Processing rejected fraudulent transaction',
        SystemError::PROCESSING_TIME_OUT => 'Processing timeout error',
        SystemError::REFUSAL_BY_GATE => 'Transaction rejected by gateway',
        SystemError::THREE_DS_ATTEMPTS_FAIL => '3DS authorisation unsuccessful',
        SystemError::THREE_DS_AUTH_ERROR => '3DS authorisation error',
        SystemError::THREE_DS_ERROR => '3DS payment error',
        SystemError::THREE_DS_FAIL => '3DS service error',
        SystemError::THREE_DS_NOT_ATTEMPTED => '3DS not entered',
        SystemError::THREE_DS_NOTENROLLED => 'Card does not use 3DS system',
        SystemError::THREE_DS_TIME_OUT => '3DS timeout exceeded',
        SystemError::THREE_DS_USER_AUTH_FAIL => 'Incorrect 3DS code entered',
        SystemError::UNKNOWN_STATE => 'Unknown transaction status',
        SystemError::USER_NOT_FOUND => 'User not found',
        SystemError::WRONG_AUTHORIZATION_CODE => 'Incorrect authorisation code',
        SystemError::WRONG_CARD_INFO => 'Incorrect card details',
        SystemError::WRONG_CARDHOLDER => 'Invalid card holder',
        SystemError::WRONG_CONFIRM_CODE => 'Invalid authorisation code',
        SystemError::WRONG_CVV => 'Invalid CVV',
        SystemError::WRONG_EXPIRE_DATE => 'Incorrect valid through date',
        SystemError::WRONG_PAN => 'Incorrect card number',
        SystemError::WRONG_PARAMS => 'Incorrect parameters',
        SystemError::WRONG_PAY_INFO => 'Incorrect card data in gateway',
        SystemError::WRONG_PHONE => 'Incorrect telephone number',
        SystemError::WRONG_USER_PARAMS => 'Incorrect user parameters',
        SystemError::OTHER_ERROR => 'Error due to impossible combination of circumstances',
        SystemError::AMOUNT_EXCEED_BALANCE => 'Unfortunately, at present, the payment from the card is impossible. Please contact your Bank and try again, or use another card',
        SystemError::AUTHENTICATION_ERROR => 'Unfortunately, at present, the payment from the card is impossible. Please contact your Bank and try again, or use another card',
        SystemError::AUTHORIZATION_TIMEOUT => 'Unfortunately, at present, the payment from the card is impossible. Please contact your Bank and try again, or use another card',
        SystemError::LIMIT_EXCHAUST => 'Time allocated for input data is exhausted. Please place a new order',
        SystemError::WRONG_CARD_PAN => 'Invalid card number. Please repeat input',
    ];
}
