<?php

namespace Omnipay\Payture\Exception\ru;

use Omnipay\Payture\Exception\LocalizedError;
use Omnipay\Payture\Exception\SystemError;

/**
 * Payture protocol errors russian localization.
 */
class HumanError extends LocalizedError
{
    protected static $_errors = [
        SystemError::SUCCESS => null,
        SystemError::UNKNOWN => 'К сожалению, в настоящее время платеж с данной карты невозможен. Попробуйте оплатить другой картой',
        SystemError::ACCESS_DENIED => 'Запрещены операции с данным набором параметров для терминала',
        SystemError::AMOUNT_ERROR => 'Ошибка суммы операции. Превышена сумма либо сумма операции не проверена в биллинге',
        SystemError::AMOUNT_EXCEED => 'Сумма транзакции превышает доступный остаток средств на выбранном счете',
        SystemError::API_NOT_ALLOWED => 'Запрет использования API с данного IP проверьте реквизиты доступа',
        SystemError::CARD_EXPIRED => 'Истек срок действия карты',
        SystemError::CARD_NOT_FOUND => 'Не найдена карта по данному идентификатору',
        SystemError::COMMUNICATE_ERROR => 'Ошибка связи в физических каналах',
        SystemError::CURRENCY_NOT_ALLOWED => 'Валюта не разрешена для предприятия',
        SystemError::CUSTOMER_NOT_FOUND => 'Пользователь не найден',
        SystemError::DUPLICATE_CARD => 'Карта уже существует',
        SystemError::DUPLICATE_ORDER_ID => 'Заказ существует в Payture с данным идентификатором',
        SystemError::DUPLICATE_PROCESSING_ORDER_ID => 'Заказ существует в процессинге с данным идентификатором',
        SystemError::DUPLICATE_USER => 'Пользователь уже существует',
        SystemError::EMAIL_ERROR => 'Ошибка при обработке сообщения электронной почты ошибка отправки сообщения',
        SystemError::EMPTY_RESPONSE => 'Пустой ответ',
        SystemError::FRAUD_ERROR => 'Ошибка связанная с мошенничеством',
        SystemError::FRAUD_ERROR_BIN_LIMIT => 'Превышение оплат с 1 банка',
        SystemError::FRAUD_ERROR_BLACKLIST_AEROPORT => 'Аэропорт в черном списке мошеннических',
        SystemError::FRAUD_ERROR_BLACKLIST_BANKCOUNTRY => 'Страна банка в черном списке мошеннических',
        SystemError::FRAUD_ERROR_BLACKLIST_USERCOUNTRY => 'Страна пользователя в черном списке мошеннических',
        SystemError::FRAUD_ERROR_CRITICAL_CARD => 'Карта помечена как мошенническая',
        SystemError::FRAUD_ERROR_CRITICAL_CUSTOMER => 'Пользователь помечен как мошенник',
        SystemError::FRAUD_ERROR_IP => 'IP помечен как мошеннический',
        SystemError::FRAUD_INTERNAL_ERROR => 'Ошибка антифрод фильтра при обработке транзакции',
        SystemError::ILLEGAL_ORDER_STATE => 'Неверное состояние заказа',
        SystemError::INTERNAL_ERROR => 'Внутренняя ошибка шлюза',
        SystemError::INVALID_PAYTUREID => 'Неверный fingerprint устройства',
        SystemError::INVALID_SIGNATURE => 'Неверная подпись запроса',
        SystemError::ISSUER_BLOCKED_CARD => 'Карта заблокирована у эмитента',
        SystemError::ISSUER_CARD_FAIL => 'Эмитент не смог разрешить списание средств с карты',
        SystemError::ISSUER_FAIL => 'Эмитент не ответил на запрос',
        SystemError::ISSUER_LIMIT_AMOUNT_FAIL => 'Превышение лимитов на сумму у эмитента',
        SystemError::ISSUER_LIMIT_COUNT_FAIL => 'Превышение лимитов на количество операций у эмитента',
        SystemError::ISSUER_LIMIT_FAIL => 'Превышение лимитов у эмитента(без расшифровки)',
        SystemError::ISSUER_TIMEOUT => 'Эмитент не ответил в установленное время',
        SystemError::MERCHANT_FORWARD => 'Перенаправление на другой терминал',
        SystemError::MERCHANT_RESTRICTION => 'Запрет МПС или экваера на проведение операции мерчанту',
        SystemError::MPI_CERTIFICATE_ERROR => 'Ошибка сервиса MPI(шлюз)',
        SystemError::MPI_RESPONSE_ERROR => 'Ошибка сервиса MPI(МПС)',
        SystemError::ORDER_NOT_FOUND => 'Заказ не найден',
        SystemError::ORDER_TIME_OUT => 'Заказ просрочен',
        SystemError::PAYMENT_ENGINE_ERROR => 'Ошибка взаимодействия в ядре процессинга',
        SystemError::PROCESSING_ACCESS_DENIED => 'Доступ к процессингу запрещен',
        SystemError::PROCESSING_ERROR => 'Ошибка при процессинге платежа',
        SystemError::PROCESSING_FRAUD_ERROR => 'Процессинг отклонил мошенническую транзакцию',
        SystemError::PROCESSING_TIME_OUT => 'Не получен ответ от процессинга в установленное время',
        SystemError::REFUSAL_BY_GATE => 'Операция отклонена шлюзом',
        SystemError::THREE_DS_ATTEMPTS_FAIL => 'Попытка 3DS авторизации неудачна',
        SystemError::THREE_DS_AUTH_ERROR => 'Ошибка авторизации 3DS',
        SystemError::THREE_DS_ERROR => 'Ошибка оплаты 3DS',
        SystemError::THREE_DS_FAIL => 'Ошибка сервиса 3DS',
        SystemError::THREE_DS_NOT_ATTEMPTED => '3DS не вводился',
        SystemError::THREE_DS_NOTENROLLED => 'Карта не вовлечена в систему 3DS',
        SystemError::THREE_DS_TIME_OUT => 'Превышено время ожидания 3DS',
        SystemError::THREE_DS_USER_AUTH_FAIL => 'Пользователь ввел неверный код 3DS',
        SystemError::UNKNOWN_STATE => 'Неизвестный статус транзакции',
        SystemError::USER_NOT_FOUND => 'Пользователь не найден',
        SystemError::WRONG_AUTHORIZATION_CODE => 'Неверный код авторизации',
        SystemError::WRONG_CARD_INFO => 'Неверная информация на карте',
        SystemError::WRONG_CARDHOLDER => 'Недопустимый кардхолдер',
        SystemError::WRONG_CONFIRM_CODE => 'Недопустимый код подтверждения',
        SystemError::WRONG_CVV => 'Недопустимый CVV',
        SystemError::WRONG_EXPIRE_DATE => 'Неправильная дата окончания срока действия',
        SystemError::WRONG_PAN => 'Неверный номер нарты',
        SystemError::WRONG_PARAMS => 'Неверные параметры',
        SystemError::WRONG_PAY_INFO => 'Неверные карточные данные в шлюзе',
        SystemError::WRONG_PHONE => 'Неверный телефон',
        SystemError::WRONG_USER_PARAMS => 'Неверные параметры пользователя',
        SystemError::OTHER_ERROR => 'Ошибка которая произошла при невозможном стечении обстоятельств',
        SystemError::AMOUNT_EXCEED_BALANCE => 'К сожалению, в настоящее время платеж с данной карты невозможен. Пожалуйста, свяжитесь со своим банком и попробуйте еще раз, либо воспользуйтесь другой картой',
        SystemError::AUTHENTICATION_ERROR => 'К сожалению, в настоящее время платеж с данной карты невозможен. Пожалуйста, свяжитесь со своим банком и попробуйте еще раз, либо воспользуйтесь другой картой',
        SystemError::AUTHORIZATION_TIMEOUT => 'К сожалению, в настоящее время платеж с данной карты невозможен. Пожалуйста, свяжитесь со своим банком и попробуйте еще раз, либо воспользуйтесь другой картой',
        SystemError::LIMIT_EXCHAUST => 'Время, отведенное для ввода данных, исчерпано. Пожалуйста, оформите новый заказ',
        SystemError::WRONG_CARD_PAN => 'Неверный номер карты. Пожалуйста, повторите ввод данных',
    ];
}
